### ISSUE TITLE
Tracking issues for release

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/developer#118]
P1 - we should fix before the release

- [x] Navbar links to `spin` and  needs to be fixed (remove trailing slash from href)
- [x] Link copy is not working (mouse over to any heading, link icon show up, but do nothing)
- [x] Contributing link is broken
- [x] #120
- [x] #121

P2 - we should probably fix, but after release

- [x] #122

P3 - just a suggestion, we can discuss to decide if it makes sense or not

- [x] #123
- [x] #124

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.
